version: "3.8"

services:
  lets-watch:
    build:
      # Hmm, I might want the context to be ./server, or maybe not...
      context: .
    ports:
      - 4000:4000
      - 9229:9229
    env_file: .env
    volumes:
      - ./server:/app
    # Debugger setup from https://docs.docker.com/language/nodejs/develop/#connect-a-debugger
    # I can setup debugger in VS Code with the following info, but for now things are ok.
    # https://code.visualstudio.com/docs/remote/containers
    command: npm run debug

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  postgres:
    image: postgres:13-alpine
    env_file: .env.db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgresdb:/var/lib/postgresql/data
    ports:
      - 5434:5432
      # Not sure why this differs here, I wonder if it's necessary...

volumes:
  postgresdb:
